# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r_github_packages: jdreyf/ezlimma
bioc_packages: limma
after_success:
    - Rscript -e 'covr::codecov()'
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'